### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by Bryce1010** [Bryce1010/DeepLearning-Project#12]
## 综述
- (2020) Image Segmentation Using Deep Learning:A Survey [[paper]](https://arxiv.org/pdf/2001.05566.pdf)  

- The 2018 DAVIS Challenge on Video Object Segmentation [[paper]](https://arxiv.org/pdf/1803.00557.pdf)
- [ ]  Image Segmentation: tips and tricks from 39 Kaggle competitions [[blog]](https://neptune.ai/blog/image-segmentation-tips-and-tricks-from-kaggle-competitions)
- [ ] Image segmentation in 2020: Architectures, Losses, Datasets, and Frameworks [[blog]](https://neptune.ai/blog/image-segmentation-in-2020)

**Comment by Bryce1010** [comment]
## Object Segmentation  
- [ ] (2019.04) DFANet: Deep Feature Aggregation for Real-Time Semantic Segmentation [[paper]](https://arxiv.org/abs/1904.02216)

**Comment by Bryce1010** [comment]
## Todo

**Comment by Bryce1010** [comment]
## Todo
